apiVersion: v1
kind: Deployment
metadata:
  name: wp-app
  labels:
    app: wp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
      - name: wp-app
        image: wordpress
        ports:
        - containerPort: 80
        env:
            - name: WORDPRESS_NAME
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: BLOG_DB_NAME
            - name: WORDPRESS_USER
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: BLOG_DB_USERNAME
            - name: WORDPRESS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: BLOG_DB_PASSWORD
            - name: WORDPRESS_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: BLOG_DB_HOST