---
apiVersion: v1
kind: Pod
metadata:
  name: wordpress
spec:
  containers:
    - image: wordpress
      name: wordpress
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_HOST
          value: db
        - name: WORDPRESS_DB_USER
          value: exampleuser
        - name: WORDPRESS_DB_PASSWORD
          value: examplepass
        - name: WORDPRESS_DB_NAME
          value: exampledb