---
apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
    - image: mysql:5.7
      name: db
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: exampledb
        - name: MYSQL_USER
          value: exampleuser
        - name: MYSQL_PASSWORD
          value: examplepass
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: '1'