---
apiVersion: v1
kind: Service
metadata:
  name: wp-app
spec:
  selector:
    app: wp-app
  ports:
    - nodePort: 32000
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort